# This is a basic workflow to help you get started with Actions

name: Create and publish a Product on Amplify Marketplace

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  publish-product:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      #required to be able to install the central cli added by jorism
      - name: Install libsecret
        run: sudo apt-get update && sudo apt-get install -y libsecret-1-dev

      # Prepare Axway CLI on this container
      - name: Install Axway CLI
        run: |
          npm i -g axway
          axway pm install @axway/axway-central-cli
      
      # Runs a set of commands using the runners shell
      - name: Show current Axway team
        run: axway config list
        #Set the team context explicitely here ;
      - name: Set Axway team context
        run: axway config set central.team Portal\ Development
      - name: Create Asset, Product, and publish Product to Marketplace
        env:
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        run: |
          ./create-n-publish-product.sh
        shell: bash
        # for debugging reasons only continue on error
        continue-on-error: true

      #cat the output file. in case of an error more info is in here
      - name: Show asset creation output
        run: cat ./json_files/asset-created.json
